PATH_TO_DOOR_IMG = "src/tile_sets/tiles_for_map/doors/down_doors/sprite_0.png"
PATH_TO_EMPTY_IMG = "src/tile_sets/tiles_for_map/back_ground/sprite_078.png"
PATH_TO_LEFT_DOWN_IN_CORNER = "src/tile_sets/tiles_for_map/left_down_corner/in_corner.png"
PATH_TO_LEFT_DOWN_OUT_CORNER = "src/tile_sets/tiles_for_map/left_down_corner/out_corner.png"
PATH_TO_RIGHT_DOWN_IN_CORNER = "src/tile_sets/tiles_for_map/right_down_corner/in_corner.png"
PATH_TO_RIGHT_DOWN_OUT_CORNER = "src/tile_sets/tiles_for_map/right_down_corner/out_corner.png"
PATH_TO_UP_WALLS = "src/tile_sets/tiles_for_map/up_walls/sprite_"
PATH_TO_DOWN_WALLS = "src/tile_sets/tiles_for_map/down_walls/sprite_"
PATH_TO_RIGHT_WALLS = "src/tile_sets/tiles_for_map/right_walls/sprite_"
PATH_TO_LEFT_WALLS = "src/tile_sets/tiles_for_map/left_walls/sprite_"
PATH_TO_FLOORS = "src/tile_sets/tiles_for_map/floor/sprite_"
PATH_TO_CHARACTER = "src/tile_sets/tiles_for_chars/sprite_0.png"
PATH_TO_CHARACTER_ON_MINI_MAP = "src/tile_sets/tiles_for_chars/sprite_1.png"
EXTENSION_OF_IMG_FILES = ".png"

PATH_TO_CLOSED_LEFT_DOOR = "src/tile_sets/tiles_for_map/doors/left_doors/sprite_0.png"
PATH_TO_DEFINITELY_CLOSED_LEFT_DOOR = "src/tile_sets/tiles_for_map/doors/left_doors/sprite_1.png"

PATH_TO_CLOSED_RIGHT_DOOR = "src/tile_sets/tiles_for_map/doors/right_doors/sprite_0.png"
PATH_TO_DEFINITELY_CLOSED_RIGHT_DOOR = "src/tile_sets/tiles_for_map/doors/right_doors/sprite_1.png"

PATH_TO_CLOSED_UP_DOOR = "src/tile_sets/tiles_for_map/doors/up_doors/sprite_0.png"
PATH_TO_DEFINITELY_CLOSED_UP_DOOR = "src/tile_sets/tiles_for_map/doors/up_doors/sprite_1.png"

PATH_TO_CLOSED_DOWN_DOOR = "src/tile_sets/tiles_for_map/doors/down_doors/sprite_0.png"
PATH_TO_DEFINITELY_DOWN_UP_DOOR = "src/tile_sets/tiles_for_map/doors/down_doors/sprite_1.png"

PATH_TO_BASIC_CHEST = "src/tile_sets/tiles_for_map/chests_and_other/sprite_084.png"
PATH_TO_EXIT = "src/tile_sets/tiles_for_map/exit/sprite_038.png"
PATH_TO_SKELETON = "src/tile_sets/tiles_for_chars/personages/skeleton_warior/left/sprite_0.png"
PATH_TO_ENEMY = "src/tile_sets/tiles_for_chars/personages/skeleton/skeleton_0.png"